### ISSUE TITLE
ToFix

### ISSUE THREAD

**Issue by mfreema5** [spring15wad/recofont#10]
Collection of things to fix.

**Comment by mfreema5** [comment]
teams/show should return to teams/change, not /summary

**Comment by mfreema5** [comment]
On mobile, "Team" field in recommendation/new gets numberpad, key goes into repeat mode, fills field, locks up browser.

**Comment by thedanmartin** [comment]
A view-related thing I noticed

"show" and "new" views html files need to/could be edited for alignment purposes -- who sees what?

**Comment by mfreema5** [comment]
Alignment?  There's some access control enforced by the various controllers.

**Comment by thedanmartin** [comment]
Sorry, I was referring to text alignment -- the awkward default line breaks
following colons, like:

Team Name:
RecoFont

It's sort of design OCD of mine to want those things to be on a single
line, which is easily accomplished in the view haml flies. It just makes
sense time-wise to do only adjust it in the user-facing views.

**Comment by mfreema5** [comment]
To figure out what views matter, seems like the easiest thing would be to figure out where undergrads can go via links, and to what view things like “Save” return them.  Which would have the added benefit of making sure that things are pointed to the right place.

So,  `$ tree app/views/` yields:

```
app/views/
├── attachments
│   ├── _form.html.haml
│   ├── edit.html.haml
│   ├── index.html.haml
│   ├── new.html.haml
│   └── show.html.haml
├── examples
│   ├── _form.html.haml
│   ├── edit.html.haml
│   ├── index.html.haml
│   ├── new.html.haml
│   └── show.html.haml
├── layouts
│   └── application.html.erb
├── recommendations
│   ├── _form.html.haml
│   ├── edit.html.haml
│   ├── index.html.haml
│   ├── new.html.haml
│   ├── show.html.haml
│   └── summary.html.haml
├── teams
│   ├── _form.html.haml
│   ├── _pickteam.html.haml
│   ├── change.html.haml
│   ├── edit.html.haml
│   ├── index.html.haml
│   ├── landing.html.haml
│   ├── new.html.haml
│   └── show.html.haml
└── users
    ├── _form.html.haml
    ├── edit.html.haml
    ├── index.html.haml
    ├── new.html.haml
    ├── show.html.haml
    └── update.html.haml
```

Undergrads should see what?  Maybe:

```
app/views/
├── recommendations
│   └── summary.html.haml
└── teams
    ├── _form.html.haml
    ├── _pickteam.html.haml
    ├── change.html.haml
    ├── edit.html.haml
    ├── landing.html.haml
    ├── new.html.haml
    └── show.html.haml
```

Maybe check the styling for those views, and check the paths in those views and `teams_controller.rb`?

**Comment by thedanmartin** [comment]
Oh shit, I've never seen `tree` before, that is great.

**Comment by mfreema5** [comment]
Borked attachments likely has to do with passing the `example_id` around as part of the `params`.  For some reason it's not carrying over on the Heroku instance.  Might need to decipher the `form_for` helper and see if there's some way to make sure it gets sent.

**Comment by thedanmartin** [comment]
What is the default view for /teams? landing.html.haml?

**Comment by mfreema5** [comment]
Landing.html.haml is the “Begin” page.  (Put directions on that?)

Default for teams is  “/teams/change” or summat.  If “/teams” doesn't redirect there, it probably should (config/routes.rb).

**Comment by mfreema5** [comment]
Yeah, ‘/team’ isn't redirected.  See: [heroku2/config/routes.rb](https://github.com/spring15wad/recofont/blob/81b6855375a466966edf82601fb43bd03ec9be2d/config/routes.rb).

Need something like:

```
get '/teams', to: redirect('/change_teams'), as: 'teams'

resources :teams, except: :destroy :index
```

**Comment by mfreema5** [comment]
Attachments work!

If you “show” a recommendation, there's a button to “add example”.  Using that button automatically sets the `recommendation_id`.

If you “show” an example, there's a button to “add attachment”.  Using that button automatically sets the `example_id`.

Manually set the url to `/recommendations`, and you can use links to get around to all the non-undergrad pages, AFAIK.

---

To deploy:

Pull `heroku2`, merge with all the styling updates you've made on `heroku` or whatever, and push it to heroku with `git push heroku local_branch:master`

Get the database URL, by running: `heroku pg:info`

Reset the database with: `heroku pg:reset [database_URL]`

Then:

```
$ heroku run rake db:migrate

$ heroku run rake db:seed
```

And it should be live.  Send link to Karl, etc.

**Comment by thedanmartin** [comment]
I don't get a database URL when running `heroku pg:info`

$ heroku pg:info
=== HEROKU_POSTGRESQL_TEAL_URL (DATABASE_URL)
Plan:        Hobby-dev
Status:      Available
Connections: 1/20
PG Version:  9.4.1
Created:     2015-04-28 21:04 UTC
Data Size:   7.2 MB
Tables:      6
Rows:        0/10000 (In compliance)
Fork/Follow: Unsupported
Rollback:    Unsupported

**Comment by mfreema5** [comment]
> === HEROKU_POSTGRESQL_TEAL_URL (DATABASE_URL)

$ heroku pg:reset HEROKU_POSTGRESQL_TEAL_URL

**Comment by thedanmartin** [comment]
Fuck, I was expecting an actual http:// URL.

**Comment by mfreema5** [comment]
Oh, BTW, I don't think we need Karl to distribute the web address to the undergrads—AFAIK, Blackboard will let you send an email to everyone in a course.
