### ISSUE TITLE
No user names; not changing teams

### ISSUE THREAD

**Issue by mfreema5** [spring15wad/recofont#11]
New users aren't getting names. Is that a bug?

They also aren't changing teams after making a new one. Too confusing, or unable to change?

**Comment by mfreema5** [comment]
Apparently, "name" is optional.  Should've used "login".

**Comment by mfreema5** [comment]
I've removed the call to `allow_users` from `users_controller.rb` on the off chance that it's causing problems.  I manually added GH-usernames as usernames for existing users.  (I tried to change the model to use `login`, but it failed, and I'm not going to try debugging that right now.)

More importantly, I've changed `app/views/users/_form.html.haml` to select teams by project name.  This means we can go in and change a user's teams for him/her.

I pushed these changes to the test instance, and they didn't break anything.  They should be pushed to the production instance, IMO.

**Comment by thedanmartin** [comment]
I pulled and pushed to the production URL.

**Comment by mfreema5** [comment]
Thanks.  I went in and moved users to teams.  For one user, I first had to create their team.  Presumably I picked the right repo from their account.

And, for the hell of it, created a RollingRead team.

**Comment by mfreema5** [comment]
Another problem: a team without a recommendation breaks the `/summary` page.

I added a conditional to the form to handle that.  Checked it on the test instance and it worked.  Merged into `master` and pushed it to GitHub.

Please pull it and push to production.

**Comment by thedanmartin** [comment]
I'm not home until roughly 7 with only my phone, and I haven't installed a
terminal app on it just yet, so in case you keep seeing this happen, that's
why. Will take care of it as soon as I return.

**Comment by mfreema5** [comment]
Thanks for letting me know.

**Comment by thedanmartin** [comment]
I don't know what the hell is going on, but after pulling the master branch
and trying to push it to heroku git is telling me that my local branch is
ahead of master by 4 commits, so it won't push. I'm on the master branch,
everything is up to date, I don't understand.

**Comment by thedanmartin** [comment]
Never mind, I remembered the -f flag. Hope nothing's broken.

**Comment by mfreema5** [comment]
Hope it's okay. My internet at home has stopped connecting to DNS.  Dunno when it will be working again.  I'm connected through a phone to write this.
