### ISSUE TITLE
No recommendation for team “A+”

### ISSUE THREAD

**Issue by mfreema5** [spring15wad/recofont#14]

**Comment by thedanmartin** [comment]
Cloned this locally to take a look and get started on recommendation.

**Comment by jhignight** [comment]
Dan and I will be meeting to make recommendations and pull requests later
this afternoon.

Josh Hignight
Assistant Registrar
Illinois Institute of Technology
3424 S. State Street Suite 2014
Chicago, IL 60616
312.567.5791
http://iit.edu/registrar

**Comment by mfreema5** [comment]
I'm guessing this will be useful: [docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x/).

**Comment by mfreema5** [comment]
Twitter apps, in case you haven't already figured it out, don't allow `localhost`.  Instead, use:

```
http://127.0.0.1:3000/
http://127.0.0.1:3000//auth/twitter/callback
```

Though the callback may be different for each project.  I'm not sure where to look for that.  Maybe in  `app/controllers/application_controller.rb` or `config/routes.rb`?

**Comment by mfreema5** [comment]
Oh, and trying to find a string in the files of a Rails app:

```
find . -type f -name "*.rb" -exec grep -H "user_signed_in" "{}" \;
```

Replace “user_signed_in” with whatever you're looking for.
