### ISSUE TITLE
Serving binaries

### ISSUE THREAD

**Issue by mfreema5** [spring15wad/recofont#4]
There's a helper method, `link_to`, that converts strings into hyperlinks in views.

Is there something similar that creates a “Download” or “View” button for binary files that are stored in the app's DB?

**Comment by thedanmartin** [comment]
http://stackoverflow.com/questions/24868723/how-to-download-binary-files-from-a-database-in-rails

**Comment by thedanmartin** [comment]
So, I copied over some of the code from that stackoverflow solution and I think it might work, though I am not sure I have the syntax correct for our specific purposes.

However, in researching the situation a bit I came across this gem, which is purported to do most of the heavy lifting of uploading and downloading. Take a look? I'm not entirely sure how to implement it but if it fits our needs I will work on that.

https://github.com/thoughtbot/paperclip

**Comment by thedanmartin** [comment]
OK, I pushed up the 'binaries' branch with code sniped from the stackoverflow link above. I'm certain I haven't done it right, would appreciate a second set of eyes to help interpret what else is necessary.

I don't know if Paperclip is what we need, it seems heavily geared towards image/avatar uploading and downloading. Then again, I don't feel competent enough to determine for sure.

**Comment by mfreema5** [comment]
Not criticisms; just some notes to myself (in case I get an inclination to hack on this later).
- Why hardcode `type: 'zip'`?
- `examples/new.html.haml`:  is it missing the `form_helper`? or does the one from the `render` carry over?
  - Might the new code be better off in `_form.html.haml` anyway?
- `examples/index.html.haml` — the download link should probably be nested under `@examples.each`, so that each example gets a download button.
- I have no idea what this `params` thing does; I keep seeing it all over the intarwebs.
- Presumably `item` → `example`

---

Paperclip puts attachments into the file system, not the database.  Seems overly-complicated for RecoFont.

---

```
 app/controllers/examples_controller.rb | 16 ++++++++++++++++
 app/views/examples/index.html.haml     |  4 +++-
 app/views/examples/new.html.haml       |  5 +++++
 config/routes.rb                       |  4 +++-
```

**Comment by thedanmartin** [comment]
No worries. A lot of this is probably because I pretty much copied code directly. 

Regarding the zip type -- the original example was referencing upping and downloading zip files from a database.

My guess about "params" is that those are parameters specific to the issue in question, and people maybe just put "params" as shorthand?

And yeah, "item" == "example" -- at least I'm pretty sure it does.

**Comment by thedanmartin** [comment]
`type: 'zip'` is indeed just a result of my copy/pasting. I am pretty sure we'll be able to replace `'zip'` with `'application/pdf'`.

EDIT: I made the change from `type: 'zip'` to `type: 'application/pdf'` and also moved the download link in `examples/index.html.haml` to be nested under `@examples.each`. Pushed the revised files, too.

**Comment by thedanmartin** [comment]
Re: `params` -- http://guides.rubyonrails.org/action_controller_overview.html#parameters

Sifting through this trying to figure out whether it's relevant to our purposes or can be ignored...

**Comment by thedanmartin** [comment]
My fiddling around on my local copy has pretty definitively broken something and I can't work it out. Might just end up ditching this branch and restarting, not sure.

**Comment by mfreema5** [comment]
Branches are cheap; make as many as you want. But go ahead and commit and
push the broken one first.

**Comment by mfreema5** [comment]
Might be useful: 
- [How to save uploaded files to your database in Rails](https://gist.github.com/macek/610596)
- Rails API: [send_data(data, options = {})](http://api.rubyonrails.org/classes/ActionController/DataStreaming.html#method-i-send_data)

**Comment by thedanmartin** [comment]
~~I just stashed the edited files I had worked on and tried pulling like you mentioned -- I got a message saying I was up to date... Trying to decipher where I'm at.~~

Ugh never mind, I'm dumb and was trying to pull the master branch, not the binaries branch you had edited.

**Comment by mfreema5** [comment]
I thought maybe I was getting somewhere with uploads, but I started having issues with nested form helpers in `examples/_form.html.haml`.  

And then it occurred to me that it might be easier to put uploaded files into a separate model.  Thus, Attachments.  Committed & pushed.

All the forms and views and things still need updated.  And figuring out how to seed a binary might be helpful.

**Comment by mfreema5** [comment]
Well FML. Got everything to a point where it seems like it should work, and get this redheaded error:

`undefined method 'encoding' for #<ActionDispatch::Http::UploadedFile:0x007fdb36d19fe8>`

Googling on that reveals:

> You cannot assign a file object to a binary column and save it. ([link](http://stackoverflow.com/questions/24379662/rails-undefined-method-encoding-for-actiondispatchhttpuploadedfilexxxx))

What the bloody hell is it good for, then?  Anyway, our options would seem to be:

> If you really want to just save the file's contents to the database, call `read` on it before assigning it to your model. You probably want to do something more suited for file uploads, though. Take a look at CarrierWave and Paperclip

Maybe you were right about [Paperclip](https://github.com/thoughtbot/paperclip), Dan? Though, how would that complicate deployment, since now you're allowing write access to the host filesystem?

Going to push this borked version.  Figure out if `read` is an option later today. Re: [ActionDispatch::Http::UploadedFile < Object](http://api.rubyonrails.org/classes/ActionDispatch/Http/UploadedFile.html).

**Comment by mfreema5** [comment]
Belay that.

We **are** using the `read` method:

``` ruby
    if attachment_params[:tempfile]
      @attachment.filedata  = attachment_params[:tempfile].read
      @attachment.filename  = attachment_params[:tempfile].original_filename
      @attachment.mime_type = attachment_params[:tempfile].content_type
    end
```

And it seems to be working, because on the redheaded page:

```
Parameters:

{"utf8"=>"✓",
 "_method"=>"patch",
 "authenticity_token"=>"uDFe8PTzJRoGT08RMDiAj6y3zUZBDdc08GGhOOAMFZCWrmcrkqkZ31lPx3kqpJU6c9N1bXsaPhwXN3P1nOIkLg==",
 "attachment"=>{"filename"=>"Rrr.png",
 "example_id"=>"1",
 "filedata"=>#<ActionDispatch::Http::UploadedFile:0x007fd74c9c9390 @tempfile=#<Tempfile:/var/folders/dg/cqbcmtxd76x2rltsfzkntrjr0000gn/T/RackMultipart20150428-32386-1lrl9jz.png>,
 @original_filename="R.png",
 @content_type="image/png",
 @headers="Content-Disposition: form-data; name=\"attachment[filedata]\"; filename=\"R.png\"\r\nContent-Type: image/png\r\n">},
 "commit"=>"Upload",
 "id"=>"2"}
```

The thing I can't understand is that the supposedly undefined method is “`encoding`”, yet where is that being called?

``` bash
$ find . -type f -iname "*.rb" -exec grep -H "encoding" "{}" \;
./db/schema.rb: # encoding: UTF-8
```

In [https://github.com/rails/…/upload.rb](https://github.com/rails/rails/blob/90f0cdc906fcec77937363c87cba45f3802ac858/actionpack/lib/action_dispatch/http/upload.rb)  there's this:

``` ruby
        @original_filename &&= @original_filename.encode "UTF-8"
```

**Comment by mfreema5** [comment]
I was wrong about a lot of things in the above comments.  Ignore them.

The hint that solved the case came from an error in the terminal where `rails server` was running:

``` bash
Cannot render console with content type multipart/form-dataAllowed content types: [#<Mime::Type:0x007fd6ca20e5b0 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html">, #<Mime::Type:0x007fd6ca20ff00 @synonyms=[], @symbol=:text, @string="text/plain">, #<Mime::Type:0x007fd6ca1cd330 @synonyms=[], @symbol=:url_encoded_form, @string="application/x-www-form-urlencoded">]
```

The important part being **content type multipart**.  Presumably this why in the Gist [How to save uploaded files to your database in Rails](https://gist.github.com/macek/610596), the `create` method includes a loop

``` ruby
    @photo = Photo.new(params[:photo]) do |t|
      if params[:photo][:data]
        t.data      = params[:photo][:data].read
        t.filename  = params[:photo][:data].original_filename
        t.mime_type = params[:photo][:data].content_type
      end
    end
```

I hadn't included that before.  I put in the loop, and it works.

I have no idea how to use a loop along for the `update` method, so I've just commented out that entire method in `attachment_controller.rb`.  You can't update attachments.  If one needs changed, delete it and make a new one.

Now, to embed uploading attachments in the `examples` form.  Attachments need to belong `examples`, because `examples` have descriptions to explain what the attachments are.
