### ISSUE TITLE
When user.team_id is nil route to teams/change

### ISSUE THREAD

**Issue by mfreema5** [spring15wad/recofont#6]
Users without a team should be directed to page to either pick a team, or create a team.

**Comment by thedanmartin** [comment]
I asked Karl about this, he basically said: 

all logic should go in the relevant controllers for each action -- i.e. application-level controller for authentication, recommendation controller for team selection

This is how I think am going to try & proceed -- make sure the github oauth stuff is at the application level, then work on making a team-less user pick/create a team in the recommendation controller... though it seems like maybe that ought to be in the teams controller?

**Comment by mfreema5** [comment]
Good deal.  BTW, check the addition I made to the recofont-notes on
metaWAD. If you see an opportunity along the way to check users against
that list….

Mike

**Comment by thedanmartin** [comment]
The bit about the Github ids? I'll email Karl and copy you.

**Comment by mfreema5** [comment]
Thanks.

**Comment by mfreema5** [comment]
It occurred to me it would be easier to just assign any new user to a “default team” than try to route them around based on whatever.  So, I did that.
