### ISSUE TITLE
errors I have known and loved

### ISSUE THREAD

**Issue by thedanmartin** [spring15wad/recofont#9]
These are all `/attachments` related items...

I got the "We're sorry, but something went wrong." message when uploading a new attachment (a jpeg) via https://afternoon-oasis-8842.herokuapp.com/attachments/new

When I made a new attachment without selecting a file, a new record was created just fine. I cannot edit the example name -- no name appears.

What looks like a broken image link that says "Serve" appears on the screen when I edit the attachment, see screenshot attached.

![attachments-serve](https://cloud.githubusercontent.com/assets/8630916/7418170/6a0f357c-ef31-11e4-8cd4-7dc0b6498ec1.png)

**Comment by mfreema5** [comment]
Example is an integer (example_I'd).  Attachments belong to examples. 

Broken image icon is expected.

"Something went wrong" might be an issue with example_id. Might-should validate that.

**Comment by thedanmartin** [comment]
/examples...

"http://$$$$$$$$$$$" is accepted as a valid URL but "example.com" is not. Dunno if this is worth fixing really...

Can enter no Description, URL, or Recommendation at all and still create a record.

I entered a really big number "101002302395969234" in Recommendation and a link back to `examples/new` in the examples URL window and got the "something went wrong" error. Screenshot attached. 

![examples-bignumber](https://cloud.githubusercontent.com/assets/8630916/7418780/25b53890-ef36-11e4-8bbb-2e4619645a17.png)

**Comment by thedanmartin** [comment]
`/recommendations'

I got the "something went wrong" error when I entered the information in the screenshot below

![recommendations-broken](https://cloud.githubusercontent.com/assets/8630916/7418955/61d87552-ef37-11e4-8886-eebb6e217e0a.png)

When I changed the URL to example.com and the team to 1, everything worked and it linked up with team 1's example information.

**Comment by thedanmartin** [comment]
In /attachments, I uploaded a jpeg successfully, then clicked show, then edit, and tried to upload a different jpeg, and got the "something went wrong" error when I hit the "upload" button.

**Comment by jhignight** [comment]
I'm trying to find the validation specs. Could it be a validation error?

Josh Hignight
Assistant Registrar
Illinois Institute of Technology
3424 S. State Street Suite 2014
Chicago, IL 60616
312.567.5791
http://iit.edu/registrar

**Comment by mfreema5** [comment]
Yes, it's going to throw a “foreign key” error any time you try to create a record that `belongs_to` some other record that doesn't exist.  Maybe throw a select_collection on the form?  Or validate things (in the controller? in the model?), but I have no clue how to do that.

And yes, the URL checking is simplistic.  All it does is look for `http` at the start.  Go check the model. The validation is not (in my brain) intended to prevent bad URLs, but to prevent the summary pages from puking when they try to do `regex` on the fields in order to make prettier strings for presentation.

**Comment by mfreema5** [comment]
You shouldn't be able to get to `attachments` directly anymore.  Instead, you got to an example without an attachment, and add one through a link or button.  There can be only one attachment per example. (Destroying attachments may redirect to a dead end—I'm not sure.)  Doing it this way adds the `example_id` automatically to the `attachment` record.

I didn't have time to do the same thing for examples, creating them from their recommendations.  But I did manage to replace the generic field with a list of the team_ID that to which the recommendations are tied.  Every team should only have one recommendation (though, that's not enforced).

ASCII diagram of relationships:

```
team ── recommendation ─── example ── attachment
               │     └─── example
               └─────── example ── attachment
```

Just checked, and **attachments are completely broken.**  Work perfectly on the local instance, so it should be a fucking JOY to figure out the problem.

Pushing new branch, `heroku2`.
